[build]
  command = "yarn build"
  publish = ".vuepress/dist/"

# This replaces the meta refresh with an HTTP refresh that doesn't have an
# index.html suffix
[[redirects]]
  from = "/"
  to = "/learn"
  status = 302
